[package]
name = "FedStorageServer-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
num-derive = "0.4.2"
num-traits = "0.2.19"
tokio = { version = "^1.43", features = ["rt-multi-thread","net","sync","io-util"] }
